Run python main.py
  python main.py
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.11.12/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.11.12/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.12/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.12/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.12/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.11.12/x64/lib
Traceback (most recent call last):
üì• Domain response: {'@context': '/contexts/Domain', '@id': '/domains', '@type': 'hydra:Collection', 'hydra:totalItems': 1, 'hydra:member': [{'@id': '/domains/683e285734eb9ac6bea7bca6', '@type': 'Domain', 'id': '683e285734eb9ac6bea7bca6', 'domain': 'punkproof.com', 'isActive': True, 'isPrivate': False, 'createdAt': '2025-06-02T00:00:00+00:00', 'updatedAt': '2025-06-02T00:00:00+00:00'}]}
  File "/home/runner/work/tamil-news/tamil-news/main.py", line 38, in <module>
üì§ Account creation response: 201 {"@context":"\/contexts\/Account","@id":"\/accounts\/6841407642395339b50379ac","@type":"Account","id":"6841407642395339b50379ac","address":"news_2e014a3d@punkproof.com","quota":40000000,"used":0,"isDisabled":false,"isDeleted":false,"createdAt":"2025-06-05T07:00:06+00:00","updatedAt":"2025-06-05T07:00:06+00:00"}
    main()
  File "/home/runner/work/tamil-news/tamil-news/main.py", line 13, in main
    openai_signup(driver, mail_client)
  File "/home/runner/work/tamil-news/tamil-news/src/openai_signup.py", line 37, in openai_signup
    email = mail_client.account['email']
            ^^^^^^^^^^^^^^^^^^^
AttributeError: 'MailTMClient' object has no attribute 'account'
üîê Token response: 200 {"token":"***","@id":"\/accounts\/6841407642395339b50379ac","id":"6841407642395339b50379ac"}
‚úÖ Account ready: news_2e014a3d@punkproof.com
üîê Signing up for OpenAI...
Error: Process completed with exit code 1.
